//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDRESS
    {
        public int address_id { get; set; }
        public int student_id { get; set; }
        public string address_line { get; set; }
        public string city { get; set; }
        public string zip_postcode { get; set; }
        public string state { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
    }
}
